import { useState } from "react"
import { ArrowRight, Eye, Printer } from "lucide-react"
export function StudyGuides({ chapters, selectedChapter, onSelectChapter, onPractice, cramDecks }) {
  const [revealed, setRevealed] = useState(false)
  const chapter = chapters.find(item => item.id === selectedChapter.id) ?? chapters[0]
  return <div className="space-y-5 guide-print">
    <section className="panel p-6"><div className="section-heading"><div><p className="eyebrow">Study guides</p><h2 className="mt-1 text-3xl font-semibold">Understand it. Explain it. Remember it.</h2><p className="mt-3 text-sm text-slate-600">Start without the answers. Sketch the relationships or explain them aloud, then check the course notes.</p></div><button className="action action-secondary print-hidden" onClick={() => window.print()}><Printer size={16}/> Print guide</button></div><label className="field mt-5 print-hidden"><span>Chapter guide</span><select value={chapter.id} onChange={event => { onSelectChapter(event.target.value); setRevealed(false) }}>{chapters.map(item => <option key={item.id} value={item.id}>Chapter {item.number} — {item.title}</option>)}</select></label></section>
    <section className="panel p-6"><span className="source-tag">{chapter.sourceType === "supplemental" ? "Supplemental" : "Course-based study material"}</span><h2 className="mt-3 text-2xl font-semibold">{chapter.title}</h2><div className="guide-columns mt-6"><div><p className="eyebrow">01 / Retrieve</p><h3>What can you explain from memory?</h3><ol className="guide-questions">{(chapter.reviewQuestions.length ? chapter.reviewQuestions : ["What are the main ideas in these notes?", "Which terms can you explain without looking?"]).map(question => <li key={question}>{question}<div className="writing-lines" aria-hidden="true"/></li>)}</ol></div><div><p className="eyebrow">02 / Connect</p><h3>Put the ideas on a page.</h3><p className="text-sm leading-7 text-slate-600 mt-3">Draw a map connecting the key terms. Add arrows and explain each relationship using this chapter’s notes.</p><div className="concept-cloud">{chapter.vocabulary.map(term => <span key={term}>{term}</span>)}</div><div className="sketch-space" aria-label="Space for your diagram when printed"><span>Your concept map goes here.</span></div></div></div><button className="action action-secondary mt-5 print-hidden" onClick={() => setRevealed(!revealed)} aria-expanded={revealed}><Eye size={16}/>{revealed ? "Hide course notes" : "Check the course notes"}</button><div className={`guide-answer ${revealed ? "is-revealed" : ""}`}><h3 className="text-xl font-semibold mt-6">03 / Check your understanding</h3><p className="whitespace-pre-wrap mt-3 text-sm leading-7 text-slate-700">{chapter.notes || chapter.detailSummary}</p><ul className="mt-4 space-y-3">{chapter.mustKnow.map(item => <li className="text-sm leading-6" key={item}>{item}</li>)}</ul>{chapter.commonConfusions.length > 0 && <><h4 className="mt-5 font-semibold">Watch for these confusions</h4><ul className="mt-3 space-y-3">{chapter.commonConfusions.map(item => <li className="text-sm leading-6 text-slate-700" key={item}>{item}</li>)}</ul></>}</div></section>
    <button className="action print-hidden" onClick={onPractice}>Put this chapter into practice <ArrowRight size={16}/></button>
    <details className="panel p-6 print-hidden"><summary className="font-semibold cursor-pointer">Original quick review sheets</summary><div className="grid gap-4 md:grid-cols-2 mt-5">{cramDecks.map(deck => <article key={deck.id}><p className="eyebrow">{deck.label} / course-based</p><h3 className="mt-2 text-lg font-semibold">{deck.title}</h3><ul className="mt-3 space-y-2 text-sm leading-6">{deck.mustKnow.map(item => <li key={item}>{item}</li>)}</ul><h4 className="mt-4 font-semibold text-sm">Common mistakes</h4><ul className="mt-2 space-y-2 text-sm leading-6">{deck.mistakes.map(item => <li key={item}>{item}</li>)}</ul></article>)}</div></details>
  </div>
}
