import { ArrowRight, BookOpen, Brain, Layers3, ScanLine } from "lucide-react"
export function StudyDesk({ chapters, metrics, studyState, onNavigate, onSelectChapter }) {
  const next = chapters.find(chapter => !studyState.chapterProgress[chapter.id]?.completed) ?? chapters[0]
  const attempts = Object.values(studyState.practiceProgress ?? {})
  const misses = attempts.flatMap(attempt => attempt.misses ?? [])
  const routes = [
    { title: "See the whole picture", description: "Pull the body apart. Find a structure. Make the connection.", icon: ScanLine, route: "human-body", number: "01", accent: "coral" },
    { title: "Make it stick", description: "Match ideas, answer questions, then recall them without cues.", icon: Brain, route: "practice", number: "02", accent: "teal" },
    { title: "Explain it yourself", description: "Turn a chapter into a compact guide and test your understanding.", icon: BookOpen, route: "cram", number: "03", accent: "gold" },
  ]
  return <div className="space-y-5">
    <section className="desk-welcome panel"><div><p className="eyebrow">A little curiosity goes a long way</p><h2>Learn the body.<br/><em>Build the picture.</em></h2><p>A useful session starts with one thing you can see, one thing you can explain, and one thing you can remember.</p><button className="action" onClick={() => onNavigate("human-body")}>Enter anatomy studio <ArrowRight size={17}/></button></div><div className="desk-session"><span className="eyebrow">YOUR NEXT CHAPTER</span><span className="chapter-number">{String(next?.number ?? 1).padStart(2, "0")}</span><h3>{next?.title}</h3><button className="action action-secondary" onClick={() => { onSelectChapter(next.id); onNavigate("chapters") }}>Continue reading <ArrowRight size={16}/></button></div></section>
    <div className="desk-stats"><div><strong>{metrics.completedReadyChapters}<small> / {metrics.totalReadyChapters}</small></strong><span>Chapters reviewed</span></div><div><strong>{metrics.knownFlashcards}</strong><span>Cards marked known</span></div><div><strong>{attempts.reduce((sum, attempt) => sum + (attempt.attempts ?? 0), 0)}</strong><span>Practice rounds completed</span></div><div><strong>{studyState.atlasNotebook?.bookmarks?.length ?? 0}</strong><span>Structures saved</span></div></div>
    <section className="study-path">{routes.map(item => { const Icon = item.icon; return <button key={item.route} className={`path-step ${item.accent}`} onClick={() => onNavigate(item.route)}><div className="path-step-top"><span>{item.number} /</span><Icon size={25}/></div><h3>{item.title}</h3><p>{item.description}</p><ArrowRight size={20}/></button> })}</section>
    <div className="grid gap-5 md:grid-cols-2"><section className="panel p-6"><p className="eyebrow">Back to the tricky bits</p><h3 className="mt-2 text-xl font-semibold">{misses.length ? `${new Set(misses.map(item => item.questionId)).size} questions to revisit` : "Your review list starts here"}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{misses.length ? misses[0].prompt : "Complete a practice round. Missed answers stay in the result review, ready for another try."}</p><button className="action action-secondary mt-4" onClick={() => onNavigate("practice")}>Open practice <Brain size={16}/></button></section><section className="panel p-6"><p className="eyebrow">Know your sources</p><h3 className="mt-2 text-xl font-semibold">Course first. Curiosity alongside.</h3><p className="mt-3 text-sm leading-6 text-slate-600">Your original course summaries, cards, and questions stay together. Human Atlas activities and reference descriptions are labeled supplemental. Your instructor determines exam scope.</p><button className="action action-secondary mt-4" onClick={() => onNavigate("flashcards")}>Review course cards <Layers3 size={16}/></button></section></div>
  </div>
}
